deployment:
  host: '0.0.0.0'
  port: 8000
  url: 'http://localhost'

oss:
  access_key_secret: ''
  access_key_id: ''
  endpoint: ''
  bucket_name: ''
  public_url: ''
  oss_access_key_id: ''
  oss_access_key_secret: ''
  oss_endpoint: ''
  oss_bucket_name: ''
  prefix: ''

mail:
  smtp_ssl: true
  smtp_port: 465
  smtp_port_rollback: 25
  smtp_host: ''
  smtp_host_rollback: ''
  smtp_user: ''
  smtp_password: ''
  emails_from_email: ''
  emails_from_name: ''

google_auth:
  client_id: ''
  client_secret: ''

mysql:
  mysql_host: "eurekailab.mysql.rds.aliyuncs.com"
  mysql_port: "3306"
  mysql_database: "learnique"
  mysql_user: "learnique"
  mysql_password: "EurekAILab2024_"


redis:
  redis_host: ""
  redis_port: ""
  redist_db: ""
  redis_password: ""

docs:
  username: 'eurekailab'
  password: 'eurekailab'